" vimrc, double quotes for comments
"
" Cool.
"
" A good portion of this file will be taken from
" https://vim.fandom.com/wiki/Example_vimrc
" I thank the internet for my education.

" -------------------------------------------------------------
" Features {{{1
"
" Useful stuff, for any user

" For compatibility (not 100% sure what this is)
set nocompatible

" Try to determine filetype. Used with intelligent auto-indent
" and filetype sepecific plugins.
filetype indent plugin on

" Syntax highlighting
syntax on 

" Syntax highlighting for odd extensions
autocmd BufNewFile,BufRead *.prolog set syntax=prolog

" Colour
" Set cool color
colorscheme industry

" Transparant background
hi Normal ctermbg=NONE

" Line highlighting
hi CursorLine term=bold cterm=bold ctermbg=black 

" I don't know what color 111111 is, nor do I know the appropriate values for
" ctermbg. But it produces a cool effect.
hi ColorColumn ctermbg=16 guibg=#2c2d27
set cursorline

" Set colorcolumn to show at column 80 and at column 120 onward
let &colorcolumn="80,".join(range(120,999),",")

" -------------------------------------------------------------
" Options {{{1
"
" Recommended options. Many are taken from:
" https://vim.fandom.com/wiki/Example_vimrc

" Vim with default settings does not allow easy switching between multiple files
" in the same editor window. Users can use multiple split windows or multiple
" tab pages to edit multiple files, but it is still best to enable an option to
" allow easier switching between files.
"
" One such option is the 'hidden' option, which allows you to re-use the same
" window and switch from an unsaved buffer without saving it first. Also allows
" you to keep an undo history for multiple files when re-using the same window
" in this way. Note that using persistent undo also lets you undo in multiple
" files even in the same window, but is less efficient and is actually designed
" for keeping undo history after closing Vim entirely. Vim will complain if you
" try to quit without saving, and swap files will keep you safe if your computer
" crashes.
set hidden

" Note that not everyone likes working this way (with the hidden option).
" Alternatives include using tabs or split windows instead of re-using the same
" window as mentioned above, and/or either of the following options:
" set confirm
" set autowriteall
 
" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch

" Modelines have historically been a source of security vulnerabilities. As
" such, it may be a good idea to disable them and use the securemodelines
" script, <http://www.vim.org/scripts/script.php?script_id=1876>.
" set nomodeline

" ------------------------------------------------------------
" Usability options {{{1
"
" Personal preference options.

" Case insensitive search, except when using Capital Letters
set ignorecase
set smartcase

" Allow backspacing over autoindent, line breaks and start of
" insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stops the "go to the first char of the line" thing.
set nostartofline

" Display the cursor position in the status line
set ruler

" Always display status line
set laststatus=2

" Ask to save changed files
set confirm

" Use visual bell instead of beeping
set visualbell

" Reset terminal code for visual bell.
set t_vb=

" Enable use of mouse for all modes
set mouse=a

" Set command window height to 2 lines (avoids 'press enter to contiue')
set cmdheight=2

" Display line numbers
set number
set relativenumber

" Turn off word wrap
set nowrap

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

" <F11> toggles between 'paste' & 'nopaste'
set pastetoggle=<F11>

"------------------------------------------------------------
" Indentation options {{{1

set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab

" ------------------------------------------------------------
" Mappings {{{1
"
" Useful mappings
"

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$
 
" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

" ------------------------------------------------------------
" Autocommands {{{1
"
" Auto run some commands

augroup my_au
au BufWritePost ~/notes/*.md :! ~/notes/make_html ~/notes 

" ------------------------------------------------------------
" Misc.
